import 'package:flutter/material.dart';
import '../main.dart';
final List<AnimeItem> animeList = [
  AnimeItem(
    title: 'Bleach',
    rating: 4.5,
    year: '2025',
    episodes: 24,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Bleach',
    rating: 4.5,
    year: '2025',
    episodes: 23,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Bleach',
    rating: 4.5,
    year: '2025',
    episodes: 22,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Bleach',
    rating: 4.5,
    year: '2025',
    episodes: 21,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Bleach',
    rating: 4.5,
    year: '2025',
    episodes: 20,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Bleach',
    rating: 4.5,
    year: '2025',
    episodes: 19,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Bleach',
    rating: 4.5,
    year: '2025',
    episodes: 18,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Bleach',
    rating: 4.5,
    year: '2025',
    episodes: 17,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Bleach',
    rating: 4.5,
    year: '2025',
    episodes: 16,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Bleach',
    rating: 4.5,
    year: '2025',
    episodes: 15,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Bleach',
    rating: 4.5,
    year: '2025',
    episodes: 14,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Bleach',
    rating: 4.5,
    year: '2025',
    episodes: 13,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Bleach',
    rating: 4.5,
    year: '2025',
    episodes: 12,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Bleach',
    rating: 4.5,
    year: '2025',
    episodes: 11,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Bleach',
    rating: 4.5,
    year: '2025',
    episodes: 10,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),

  AnimeItem(
    title: 'Наруто',
    rating: 4.8,
    year: '2024',
    episodes: 24,
    category: 'Шинэ гаргалтууд',
    description: 'Шиноби нарын гайхалтай түүх.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'One piece',
    rating: 5.0,
    year: '2025',
    episodes: 28,
    category: 'Шинэ гаргалтууд',
    description: 'Шинэ ертөнцийн адал явдал.',
    isLiked: false,
    imagePath: 'assets/one_piece.jpg',
    color: Colors.purple,
  ),
  AnimeItem(
    title: 'Dragon ball',
    rating: 4.7,
    year: '2025',
    episodes: 25,
    category: 'Шинэ гаргалтууд',
    description: 'Ка-мэээ-хааа-мэээ-хаааааа.',
    isLiked: false,
    imagePath: 'assets/dragon.jpg',
    color: Colors.grey,
  ),
  AnimeItem(
    title: 'Attack on titan',
    rating: 4.9,
    year: '2025',
    episodes: 26,
    category: 'Шинэ гаргалтууд',
    description: 'Үлэмж биетэн хоорондын тулаан.',
    isLiked: false,
    imagePath: 'assets/attack.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'Charlotte',
    rating: 4.6,
    year: '2025',
    episodes: 12,
    category: 'Шинэ гаргалтууд',
    description: 'Сэтгэл хөдлөм түүх.',
    isLiked: false,
    imagePath: 'assets/charlotte.jpg',
    color: Colors.amber,
  ),
  AnimeItem(
    title: 'Dandadan',
    rating: 4.9,
    year: '2025',
    episodes: 24,
    category: 'Шинэ гаргалтууд',
    description: 'Эпик адал явдал.',
    isLiked: false,
    imagePath: 'assets/dandadan.jpg',
    color: Colors.red,
  ),
  AnimeItem(
    title: 'Demon slayer',
    rating: 4.5,
    year: '2025',
    episodes: 12,
    category: 'Шинэ гаргалтууд',
    description: 'Чөтгөр усгацгаая.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.grey,
  ),
  AnimeItem(
    title: 'Slime datta ken',
    rating: 4.7,
    year: '2025',
    episodes: 12,
    category: 'Шинэ гаргалтууд',
    description: 'Өөр ертөнцөд дахин төрсөн.',
    isLiked: false,
    imagePath: 'assets/slime.jpg',
    color: Colors.pink,
  ),
  AnimeItem(
    title: 'Spy Family',
    rating: 4.8,
    year: '2025',
    episodes: 24,
    category: 'Шинэ гаргалтууд',
    description: 'One punch Anya.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.indigo,
  ),
  AnimeItem(
    title: 'Усны Шидтэн',
    rating: 4.6,
    year: '2025',
    episodes: 13,
    category: 'Шинэ гаргалтууд',
    description: 'Усны элементийг эзэмшсэн.',
    isLiked: false,
    imagePath: 'assets/water.jpg',
    color: Colors.cyan,
  ),
  AnimeItem(
    title: 'Suzume',
    rating: 4.9,
    year: '2025',
    episodes: 1,
    category: 'Шинэ гаргалтууд',
    description: 'Хоёр залуу хүний хувь заяа солилцох.',
    isLiked: false,
    imagePath: 'assets/suzume.jpg',
    color: Colors.pink,
  ),
  AnimeItem(
    title: 'Weathering With You',
    rating: 4.7,
    year: '2025',
    episodes: 1,
    category: 'Шинэ гаргалтууд',
    description: 'Цаг агаарыг хянах охин.',
    isLiked: false,
    imagePath: 'assets/weather.jpg',
    color: Colors.lightBlue,
  ),
  AnimeItem(
    title: 'A Silent Voice',
    rating: 4.8,
    year: '2025',
    episodes: 1,
    category: 'Шинэ гаргалтууд',
    description: 'Өршөөл уучлалын түүх.',
    isLiked: false,
    imagePath: 'assets/silent.jpg',
    color: Colors.purple,
  ),
  AnimeItem(
    title: 'Blame',
    rating: 4.5,
    year: '2025',
    episodes: 1,
    category: 'Шинэ гаргалтууд',
    description: 'Ёстой мэдэхгүй анимэ байна.',
    isLiked: false,
    imagePath: 'assets/blame.jpg',
    color: Colors.grey,
  ),

  AnimeItem(
    title: 'Weathering with you',
    rating: 4.5,
    year: '2025',
    episodes: 1,
    category: 'Өөр ертөнцөд өрнөдөг',
    description: 'Ёстой мэдэхгүй анимэ байна.',
    isLiked: false,
    imagePath: 'assets/weather.jpg',
    color: Colors.grey,
  ),

  AnimeItem(
    title: 'Blame',
    rating: 4.5,
    year: '2025',
    episodes: 1,
    category: 'Өөр ертөнцөд өрнөдөг',
    description: 'Ёстой мэдэхгүй анимэ байна.',
    isLiked: false,
    imagePath: 'assets/blame.jpg',
    color: Colors.grey,
  ),

  AnimeItem(
    title: 'Slime datta ken',
    rating: 4.7,
    year: '2024',
    episodes: 24,
    category: 'Өөр ертөнцөд өрнөдөг',
    description: 'Өөр ертөнцөд дахин төрсөн.',
    isLiked: false,
    imagePath: 'assets/slime.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'Re:Zero',
    rating: 4.8,
    year: '2024',
    episodes: 25,
    category: 'Өөр ертөнцөд өрнөдөг',
    description: 'Цаг хугацааг эргүүлэх чадвартай.',
    isLiked: false,
    imagePath: 'assets/blame.jpg',
    color: Colors.purple,
  ),
  AnimeItem(
    title: 'Overlord',
    rating: 4.6,
    year: '2024',
    episodes: 13,
    category: 'Өөр ертөнцөд өрнөдөг',
    description: 'Тоглоомын ертөнцөд баригдсан.',
    isLiked: false,
    imagePath: 'assets/attack.jpg',
    color: Colors.grey,
  ),
  AnimeItem(
    title: 'Sword Art Online',
    rating: 4.5,
    year: '2024',
    episodes: 24,
    category: 'Өөр ертөнцөд өрнөдөг',
    description: 'Virtual reality тоглоомын түүх.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'Konosuba',
    rating: 4.6,
    year: '2024',
    episodes: 10,
    category: 'Өөр ертөнцөд өрнөдөг',
    description: 'Инээдэм адал явдал.',
    isLiked: false,
    imagePath: 'assets/charlotte.jpg',
    color: Colors.cyan,
  ),

  AnimeItem(
    title: 'Death Note',
    rating: 5.0,
    year: '2006',
    episodes: 37,
    category: 'Онцлох',
    description: 'Оюуны тулаан.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.black,
  ),
  AnimeItem(
    title: 'Steins Gate',
    rating: 4.9,
    year: '2011',
    episodes: 24,
    category: 'Онцлох',
    description: 'Цаг хугацааны аялал.',
    isLiked: false,
    imagePath: 'assets/suzume.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Code Geass',
    rating: 4.8,
    year: '2008',
    episodes: 50,
    category: 'Онцлох',
    description: 'Эрх мэдлийн тулаан.',
    isLiked: false,
    imagePath: 'assets/attack.jpg',
    color: Colors.purple,
  ),
  AnimeItem(
    title: 'Fullmetal Alchemist',
    rating: 5.0,
    year: '2009',
    episodes: 64,
    category: 'Онцлох',
    description: 'Хамгийн шилдэг анимэ.',
    isLiked: false,
    imagePath: 'assets/dragon.jpg',
    color: Colors.yellow,
  ),
  AnimeItem(
    title: 'Hunter x Hunter',
    rating: 4.9,
    year: '2011',
    episodes: 148,
    category: 'Онцлох',
    description: 'Анчдын адал явдал.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.green,
  ),

  AnimeItem(
    title: 'Mushoku Tensei',
    rating: 4.7,
    year: '2024',
    episodes: 24,
    category: 'Дахин төрөлт',
    description: 'Шинэ амьдралд дахин эхлэл.',
    isLiked: false,
    imagePath: 'assets/slime.jpg',
    color: Colors.green,
  ),
  AnimeItem(
    title: 'The Rising of Shield Hero',
    rating: 4.6,
    year: '2024',
    episodes: 25,
    category: 'Дахин төрөлт',
    description: 'Бамбай баатар.',
    isLiked: false,
    imagePath: 'assets/attack.jpg',
    color: Colors.red,
  ),
  AnimeItem(
    title: 'Tensei Shitara',
    rating: 4.7,
    year: '2024',
    episodes: 24,
    category: 'Дахин төрөлт',
    description: 'Слайм болж төрсөн.',
    isLiked: false,
    imagePath: 'assets/water.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'Saga of Tanya',
    rating: 4.5,
    year: '2024',
    episodes: 12,
    category: 'Дахин төрөлт',
    description: 'Дайны охин.',
    isLiked: false,
    imagePath: 'assets/charlotte.jpg',
    color: Colors.brown,
  ),
  AnimeItem(
    title: 'Ascendance of Bookworm',
    rating: 4.6,
    year: '2024',
    episodes: 36,
    category: 'Дахин төрөлт',
    description: 'Номын хайртай охин.',
    isLiked: false,
    imagePath: 'assets/suzume.jpg',
    color: Colors.purple,
  ),

  // ХАЙР ДУРЛАЛ, РОМАНС - 5 ширхэг
  AnimeItem(
    title: 'Kaguya-sama',
    rating: 4.8,
    year: '2024',
    episodes: 12,
    category: 'Хайр дурлал, романс',
    description: 'Хайрын дайн.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.pink,
  ),
  AnimeItem(
    title: 'Horimiya',
    rating: 4.7,
    year: '2024',
    episodes: 13,
    category: 'Хайр дурлал, романс',
    description: 'Сургуулийн хайр.',
    isLiked: false,
    imagePath: 'assets/charlotte.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Your Lie in April',
    rating: 4.9,
    year: '2024',
    episodes: 22,
    category: 'Хайр дурлал, романс',
    description: 'Хөгжимчний хайрын түүх.',
    isLiked: false,
    imagePath: 'assets/suzume.jpg',
    color: Colors.pink,
  ),
  AnimeItem(
    title: 'Weathering With You',
    rating: 4.7,
    year: '2025',
    episodes: 1,
    category: 'Хайр дурлал, романс',
    description: 'Цаг агаарыг хянах охин.',
    isLiked: false,
    imagePath: 'assets/weather.jpg',
    color: Colors.lightBlue,
  ),
  AnimeItem(
    title: 'A Silent Voice',
    rating: 4.8,
    year: '2025',
    episodes: 1,
    category: 'Хайр дурлал, романс',
    description: 'Өршөөл уучлалын түүх.',
    isLiked: false,
    imagePath: 'assets/silent.jpg',
    color: Colors.purple,
  ),

  AnimeItem(
    title: 'Монгол анимэ 1',
    rating: 4.5,
    year: '2024',
    episodes: 12,
    category: 'Монгол',
    description: 'Монгол үйлдвэрлэлийн анимэ.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'Монгол анимэ 2',
    rating: 4.3,
    year: '2024',
    episodes: 10,
    category: 'Монгол',
    description: 'Монгол үйлдвэрлэлийн анимэ.',
    isLiked: false,
    imagePath: 'assets/dragon.jpg',
    color: Colors.green,
  ),
  AnimeItem(
    title: 'Монгол анимэ 3',
    rating: 4.4,
    year: '2024',
    episodes: 8,
    category: 'Монгол',
    description: 'Монгол үйлдвэрлэлийн анимэ.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.red,
  ),
  AnimeItem(
    title: 'Монгол анимэ 4',
    rating: 4.2,
    year: '2024',
    episodes: 15,
    category: 'Монгол',
    description: 'Монгол үйлдвэрлэлийн анимэ.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Монгол анимэ 5',
    rating: 4.6,
    year: '2024',
    episodes: 20,
    category: 'Монгол',
    description: 'Монгол үйлдвэрлэлийн анимэ.',
    isLiked: false,
    imagePath: 'assets/attack.jpg',
    color: Colors.purple,
  ),

  AnimeItem(
    title: '86',
    rating: 4.8,
    year: '2024',
    episodes: 23,
    category: 'Цэрэг, арми',
    description: 'Дайны хүнд түүх.',
    isLiked: false,
    imagePath: 'assets/attack.jpg',
    color: Colors.grey,
  ),
  AnimeItem(
    title: 'Gate',
    rating: 4.6,
    year: '2024',
    episodes: 24,
    category: 'Цэрэг, арми',
    description: 'Цэргийн адал явдал.',
    isLiked: false,
    imagePath: 'assets/dragon.jpg',
    color: Colors.green,
  ),
  AnimeItem(
    title: 'Full Metal Panic',
    rating: 4.5,
    year: '2024',
    episodes: 24,
    category: 'Цэрэг, арми',
    description: 'Робот цэргийн түүх.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'Saga of Tanya',
    rating: 4.7,
    year: '2024',
    episodes: 12,
    category: 'Цэрэг, арми',
    description: 'Дайны охины түүх.',
    isLiked: false,
    imagePath: 'assets/charlotte.jpg',
    color: Colors.brown,
  ),
  AnimeItem(
    title: 'Alderamin',
    rating: 4.4,
    year: '2024',
    episodes: 13,
    category: 'Цэрэг, арми',
    description: 'Тактикийн ухааны түүх.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.red,
  ),

  AnimeItem(
    title: 'Dr. Stone',
    rating: 4.7,
    year: '2024',
    episodes: 24,
    category: 'Шинжлэх ухаан',
    description: 'Шинжлэх ухаанаар ертөнцийг сэргээх.',
    isLiked: false,
    imagePath: 'assets/water.jpg',
    color: Colors.green,
  ),
  AnimeItem(
    title: 'Steins Gate',
    rating: 4.9,
    year: '2024',
    episodes: 24,
    category: 'Шинжлэх ухаан',
    description: 'Цаг хугацааны судалгаа.',
    isLiked: false,
    imagePath: 'assets/suzume.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Cells at Work',
    rating: 4.5,
    year: '2024',
    episodes: 13,
    category: 'Шинжлэх ухаан',
    description: 'Биологийн дэлхий.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.red,
  ),
  AnimeItem(
    title: 'Planetes',
    rating: 4.6,
    year: '2024',
    episodes: 26,
    category: 'Шинжлэх ухаан',
    description: 'Сансрын түүх.',
    isLiked: false,
    imagePath: 'assets/one_piece.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'Ghost in the Shell',
    rating: 4.8,
    year: '2024',
    episodes: 26,
    category: 'Шинжлэх ухаан',
    description: 'Кибер панк ертөнц.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.purple,
  ),

  // ХУУЧНЫ ДУРСАМЖ СЭРГЭЭМ - 5 ширхэг
  AnimeItem(
    title: 'Cowboy Bebop',
    rating: 5.0,
    year: '1998',
    episodes: 26,
    category: 'Хуучны дурсамж сэргээм',
    description: 'Классик анимэ.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'Neon Genesis Evangelion',
    rating: 4.9,
    year: '1995',
    episodes: 26,
    category: 'Хуучны дурсамж сэргээм',
    description: 'Мека робот түүх.',
    isLiked: false,
    imagePath: 'assets/attack.jpg',
    color: Colors.purple,
  ),
  AnimeItem(
    title: 'Trigun',
    rating: 4.7,
    year: '1998',
    episodes: 26,
    category: 'Хуучны дурсамж сэргээм',
    description: 'Баруун өмнөдийн sci-fi.',
    isLiked: false,
    imagePath: 'assets/dragon.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Yu Yu Hakusho',
    rating: 4.8,
    year: '1992',
    episodes: 112,
    category: 'Хуучны дурсамж сэргээм',
    description: 'Шоунэн классик.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.green,
  ),
  AnimeItem(
    title: 'Rurouni Kenshin',
    rating: 4.7,
    year: '1996',
    episodes: 94,
    category: 'Хуучны дурсамж сэргээм',
    description: 'Самурайн түүх.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.red,
  ),

  AnimeItem(
    title: 'Haikyuu',
    rating: 4.9,
    year: '2024',
    episodes: 25,
    category: 'Спорт',
    description: 'Волейболын баг.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Kuroko no Basket',
    rating: 4.7,
    year: '2024',
    episodes: 75,
    category: 'Спорт',
    description: 'Сагсан бөмбөгийн түүх.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'Slam Dunk',
    rating: 4.8,
    year: '2024',
    episodes: 101,
    category: 'Спорт',
    description: 'Сагсны классик.',
    isLiked: false,
    imagePath: 'assets/dragon.jpg',
    color: Colors.red,
  ),
  AnimeItem(
    title: 'Blue Lock',
    rating: 4.6,
    year: '2024',
    episodes: 24,
    category: 'Спорт',
    description: 'Хөлбөмбөгийн тэргүүн.',
    isLiked: false,
    imagePath: 'assets/attack.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'Hajime no Ippo',
    rating: 4.8,
    year: '2024',
    episodes: 75,
    category: 'Спорт',
    description: 'Боксчны замнал.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.brown,
  ),

  AnimeItem(
    title: 'Monster',
    rating: 4.8,
    year: '2004',
    episodes: 74,
    category: 'Мөрдлөгө',
    description: 'Гэмт хэргийн түүх.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.grey,
  ),
  AnimeItem(
    title: 'Detective Conan',
    rating: 4.7,
    year: '2024',
    episodes: 1000,
    category: 'Мөрдлөгө',
    description: 'Мөрдөгчийн түүх.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'Death Note',
    rating: 5.0,
    year: '2024',
    episodes: 37,
    category: 'Мөрдлөгө',
    description: 'Оюуны тулаан.',
    isLiked: false,
    imagePath: 'assets/silent.jpg',
    color: Colors.black,
  ),
  AnimeItem(
    title: 'Psycho-Pass',
    rating: 4.6,
    year: '2024',
    episodes: 22,
    category: 'Мөрдлөгө',
    description: 'Кибер панк мөрдөн байцаалт.',
    isLiked: false,
    imagePath: 'assets/attack.jpg',
    color: Colors.cyan,
  ),
  AnimeItem(
    title: 'Erased',
    rating: 4.7,
    year: '2024',
    episodes: 12,
    category: 'Мөрдлөгө',
    description: 'Цаг хугацааны мөрдөн байцаалт.',
    isLiked: false,
    imagePath: 'assets/suzume.jpg',
    color: Colors.blue,
  ),

  AnimeItem(
    title: 'My Hero Academia',
    rating: 4.7,
    year: '2024',
    episodes: 25,
    category: 'Онцгой хүч',
    description: 'Супер баатрууд.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.green,
  ),
  AnimeItem(
    title: 'One Punch Man',
    rating: 4.9,
    year: '2024',
    episodes: 24,
    category: 'Онцгой хүч',
    description: 'Нэг цохилтын баатар.',
    isLiked: false,
    imagePath: 'assets/dragon.jpg',
    color: Colors.yellow,
  ),
  AnimeItem(
    title: 'Mob Psycho 100',
    rating: 4.8,
    year: '2024',
    episodes: 25,
    category: 'Онцгой хүч',
    description: 'Сэтгэцийн хүч.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.purple,
  ),
  AnimeItem(
    title: 'Charlotte',
    rating: 4.6,
    year: '2024',
    episodes: 13,
    category: 'Онцгой хүч',
    description: 'Онцгой чадвартай залуучууд.',
    isLiked: false,
    imagePath: 'assets/charlotte.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'The Irregular',
    rating: 4.5,
    year: '2024',
    episodes: 26,
    category: 'Онцгой хүч',
    description: 'Ид шидийн сургууль.',
    isLiked: false,
    imagePath: 'assets/water.jpg',
    color: Colors.cyan,
  ),

  AnimeItem(
    title: 'Link Click',
    rating: 4.8,
    year: '2024',
    episodes: 12,
    category: 'Хятад',
    description: 'Хятадын анимэ.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.purple,
  ),
  AnimeItem(
    title: 'Mo Dao Zu Shi',
    rating: 4.7,
    year: '2024',
    episodes: 23,
    category: 'Хятад',
    description: 'Хятад фэнтэзи.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'The Kings Avatar',
    rating: 4.6,
    year: '2024',
    episodes: 12,
    category: 'Хятад',
    description: 'Е-спортын түүх.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Scissor Seven',
    rating: 4.5,
    year: '2024',
    episodes: 30,
    category: 'Хятад',
    description: 'Инээдтэй үйлдэл.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.red,
  ),
  AnimeItem(
    title: 'Heaven Officials Blessing',
    rating: 4.7,
    year: '2024',
    episodes: 12,
    category: 'Хятад',
    description: 'Тэнгэрийн үүлэнд.',
    isLiked: false,
    imagePath: 'assets/suzume.jpg',
    color: Colors.cyan,
  ),

  // ЦУС СОРОГЧ,ЧӨТГӨР - 5 ширхэг
  AnimeItem(
    title: 'Vampire Knight',
    rating: 4.5,
    year: '2024',
    episodes: 13,
    category: 'Цус сорогч,чөтгөр',
    description: 'Цус сорогчдын түүх.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.red,
  ),
  AnimeItem(
    title: 'Castlevania',
    rating: 4.7,
    year: '2024',
    episodes: 32,
    category: 'Цус сорогч,чөтгөр',
    description: 'Дракулагийн түүх.',
    isLiked: false,
    imagePath: 'assets/attack.jpg',
    color: Colors.grey,
  ),
  AnimeItem(
    title: 'Hellsing Ultimate',
    rating: 4.8,
    year: '2024',
    episodes: 10,
    category: 'Цус сорогч,чөтгөр',
    description: 'Цус сорогчийн анчин.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.red,
  ),
  AnimeItem(
    title: 'Seraph of the End',
    rating: 4.6,
    year: '2024',
    episodes: 24,
    category: 'Цус сорогч,чөтгөр',
    description: 'Хүмүүс эсрэг цус сорогч.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.purple,
  ),
  AnimeItem(
    title: 'Blue Exorcist',
    rating: 4.5,
    year: '2024',
    episodes: 25,
    category: 'Цус сорогч,чөтгөр',
    description: 'Чөтгөр усгацгагч.',
    isLiked: false,
    imagePath: 'assets/dragon.jpg',
    color: Colors.blue,
  ),

  // ТОГЛООМ, БООЦОО - 5 ширхэг
  AnimeItem(
    title: 'No Game No Life',
    rating: 4.6,
    year: '2024',
    episodes: 12,
    category: 'Тоглоом, бооцоо',
    description: 'Тоглоомоор ертөнцийг авах.',
    isLiked: false,
    imagePath: 'assets/charlotte.jpg',
    color: Colors.purple,
  ),
  AnimeItem(
    title: 'Kakegurui',
    rating: 4.5,
    year: '2024',
    episodes: 24,
    category: 'Тоглоом, бооцоо',
    description: 'Мөрийтэй тоглоом.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.red,
  ),
  AnimeItem(
    title: 'Death Parade',
    rating: 4.7,
    year: '2024',
    episodes: 12,
    category: 'Тоглоом, бооцоо',
    description: 'Үхлийн тоглоом.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.grey,
  ),
  AnimeItem(
    title: 'Kaiji',
    rating: 4.6,
    year: '2024',
    episodes: 26,
    category: 'Тоглоом, бооцоо',
    description: 'Азартын тоглоом.',
    isLiked: false,
    imagePath: 'assets/attack.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Tomodachi Game',
    rating: 4.4,
    year: '2024',
    episodes: 12,
    category: 'Тоглоом, бооцоо',
    description: 'Найзын тоглоом.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.blue,
  ),

  // ХӨГЖИМ - 5 ширхэг
  AnimeItem(
    title: 'Your Lie in April',
    rating: 4.9,
    year: '2024',
    episodes: 22,
    category: 'Хөгжим',
    description: 'Хөгжимчний хайрын түүх.',
    isLiked: false,
    imagePath: 'assets/suzume.jpg',
    color: Colors.pink,
  ),
  AnimeItem(
    title: 'K-On!',
    rating: 4.6,
    year: '2024',
    episodes: 39,
    category: 'Хөгжим',
    description: 'Сургуулийн хөгжмийн клуб.',
    isLiked: false,
    imagePath: 'assets/charlotte.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Nodame Cantabile',
    rating: 4.7,
    year: '2024',
    episodes: 23,
    category: 'Хөгжим',
    description: 'Сонгодог хөгжим.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.purple,
  ),
  AnimeItem(
    title: 'Beck',
    rating: 4.5,
    year: '2024',
    episodes: 26,
    category: 'Хөгжим',
    description: 'Рок хамтлагийн түүх.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.brown,
  ),
  AnimeItem(
    title: 'Given',
    rating: 4.6,
    year: '2024',
    episodes: 11,
    category: 'Хөгжим',
    description: 'BL хөгжмийн түүх.',
    isLiked: false,
    imagePath: 'assets/water.jpg',
    color: Colors.blue,
  ),

  // СҮНС - 5 ширхэг
  AnimeItem(
    title: 'Bleach',
    rating: 4.7,
    year: '2024',
    episodes: 366,
    category: 'Сүнс',
    description: 'Сүнс усгацгаая.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Yu Yu Hakusho',
    rating: 4.8,
    year: '2024',
    episodes: 112,
    category: 'Сүнс',
    description: 'Сүнсний мөрдөгч.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.green,
  ),
  AnimeItem(
    title: 'Soul Eater',
    rating: 4.6,
    year: '2024',
    episodes: 51,
    category: 'Сүнс',
    description: 'Сүнс иддэг зэвсэг.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.red,
  ),
  AnimeItem(
    title: 'Noragami',
    rating: 4.7,
    year: '2024',
    episodes: 25,
    category: 'Сүнс',
    description: 'Бурханы түүх.',
    isLiked: false,
    imagePath: 'assets/water.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'InuYasha',
    rating: 4.5,
    year: '2024',
    episodes: 167,
    category: 'Сүнс',
    description: 'Чөтгөр нохой.',
    isLiked: false,
    imagePath: 'assets/dragon.jpg',
    color: Colors.purple,
  ),

  // УРТ ҮРГЭЛЖИЛСЭН - 5 ширхэг
  AnimeItem(
    title: 'One Piece',
    rating: 5.0,
    year: '1999',
    episodes: 1100,
    category: 'Урт үргэлжилсэн',
    description: 'Далайн хулгайчдын адал явдал.',
    isLiked: false,
    imagePath: 'assets/one_piece.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'Naruto',
    rating: 4.8,
    year: '2002',
    episodes: 720,
    category: 'Урт үргэлжилсэн',
    description: 'Шиноби нарын түүх.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Bleach',
    rating: 4.7,
    year: '2004',
    episodes: 366,
    category: 'Урт үргэлжилсэн',
    description: 'Сүнс усгацгагч.',
    isLiked: false,
    imagePath: 'assets/bleach.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Dragon Ball',
    rating: 4.9,
    year: '1986',
    episodes: 640,
    category: 'Урт үргэлжилсэн',
    description: 'Классик шоунэн.',
    isLiked: false,
    imagePath: 'assets/dragon.jpg',
    color: Colors.yellow,
  ),
  AnimeItem(
    title: 'Detective Conan',
    rating: 4.6,
    year: '1996',
    episodes: 1000,
    category: 'Урт үргэлжилсэн',
    description: 'Мөрдөгчийн түүх.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.blue,
  ),

  // СУРГУУЛЬ, ӨДӨР ТУТАМ - 5 ширхэг
  AnimeItem(
    title: 'Komi Cant Communicate',
    rating: 4.6,
    year: '2024',
    episodes: 24,
    category: 'Сургууль, өдөр тутам',
    description: 'Сургуулийн амьдрал.',
    isLiked: false,
    imagePath: 'assets/charlotte.jpg',
    color: Colors.pink,
  ),
  AnimeItem(
    title: 'Horimiya',
    rating: 4.7,
    year: '2024',
    episodes: 13,
    category: 'Сургууль, өдөр тутам',
    description: 'Сургуулийн романс.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'My Teen Romantic Comedy',
    rating: 4.5,
    year: '2024',
    episodes: 38,
    category: 'Сургууль, өдөр тутам',
    description: 'Романтик инээдэм.',
    isLiked: false,
    imagePath: 'assets/suzume.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'Toradora',
    rating: 4.8,
    year: '2024',
    episodes: 25,
    category: 'Сургууль, өдөр тутам',
    description: 'Сургуулийн хайр.',
    isLiked: false,
    imagePath: 'assets/silent.jpg',
    color: Colors.pink,
  ),
  AnimeItem(
    title: 'Daily Lives of High School Boys',
    rating: 4.6,
    year: '2024',
    episodes: 12,
    category: 'Сургууль, өдөр тутам',
    description: 'Хөвгүүдийн амьдрал.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.green,
  ),

  // ИНЭЭДЭМ, ХӨГЖИЛТЭЙ - 5 ширхэг
  AnimeItem(
    title: 'Gintama',
    rating: 4.9,
    year: '2024',
    episodes: 367,
    category: 'Инээдэм, хөгжилтэй',
    description: 'Инээдтэй адал явдал.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Konosuba',
    rating: 4.7,
    year: '2024',
    episodes: 20,
    category: 'Инээдэм, хөгжилтэй',
    description: 'Инээдтэй исекай.',
    isLiked: false,
    imagePath: 'assets/charlotte.jpg',
    color: Colors.cyan,
  ),
  AnimeItem(
    title: 'Grand Blue',
    rating: 4.8,
    year: '2024',
    episodes: 12,
    category: 'Инээдэм, хөгжилтэй',
    description: 'Коллежийн амьдрал.',
    isLiked: false,
    imagePath: 'assets/water.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'Nichijou',
    rating: 4.6,
    year: '2024',
    episodes: 26,
    category: 'Инээдэм, хөгжилтэй',
    description: 'Өдөр тутмын инээдэм.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.yellow,
  ),
  AnimeItem(
    title: 'Saiki K',
    rating: 4.7,
    year: '2024',
    episodes: 120,
    category: 'Инээдэм, хөгжилтэй',
    description: 'Супер хүчтэй инээдэм.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.pink,
  ),

  // ГАРДАН ТУЛААН - 5 ширхэг
  AnimeItem(
    title: 'Kengan Ashura',
    rating: 4.5,
    year: '2024',
    episodes: 24,
    category: 'Гардан тулаан',
    description: 'Үхлийн тулаан.',
    isLiked: false,
    imagePath: 'assets/attack.jpg',
    color: Colors.red,
  ),
  AnimeItem(
    title: 'Baki',
    rating: 4.6,
    year: '2024',
    episodes: 26,
    category: 'Гардан тулаан',
    description: 'Хамгийн хүчтэй тулаанч.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.brown,
  ),
  AnimeItem(
    title: 'Hajime no Ippo',
    rating: 4.8,
    year: '2024',
    episodes: 75,
    category: 'Гардан тулаан',
    description: 'Боксчны түүх.',
    isLiked: false,
    imagePath: 'assets/dragon.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Megalo Box',
    rating: 4.5,
    year: '2024',
    episodes: 13,
    category: 'Гардан тулаан',
    description: 'Кибер бокс.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.grey,
  ),
  AnimeItem(
    title: 'Ashita no Joe',
    rating: 4.7,
    year: '2024',
    episodes: 79,
    category: 'Гардан тулаан',
    description: 'Классик бокс.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.blue,
  ),

  // ИД ШИД, ОЦГОЙ ХҮЧ - 5 ширхэг
  AnimeItem(
    title: 'Black Clover',
    rating: 4.6,
    year: '2024',
    episodes: 170,
    category: 'Ид шид, оцгой хүч',
    description: 'Ид шидийн хүч.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.green,
  ),
  AnimeItem(
    title: 'Fairy Tail',
    rating: 4.5,
    year: '2024',
    episodes: 328,
    category: 'Ид шид, оцгой хүч',
    description: 'Ид шидийн гильд.',
    isLiked: false,
    imagePath: 'assets/dragon.jpg',
    color: Colors.red,
  ),
  AnimeItem(
    title: 'Magi',
    rating: 4.6,
    year: '2024',
    episodes: 50,
    category: 'Ид шид, оцгой хүч',
    description: 'Арабын шидтэн.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'The Irregular at Magic High',
    rating: 4.5,
    year: '2024',
    episodes: 39,
    category: 'Ид шид, оцгой хүч',
    description: 'Ид шидийн сургууль.',
    isLiked: false,
    imagePath: 'assets/water.jpg',
    color: Colors.cyan,
  ),
  AnimeItem(
    title: 'Little Witch Academia',
    rating: 4.6,
    year: '2024',
    episodes: 25,
    category: 'Ид шид, оцгой хүч',
    description: 'Шидтэний академи.',
    isLiked: false,
    imagePath: 'assets/charlotte.jpg',
    color: Colors.purple,
  ),

  // ЭРОТИК - 5 ширхэг
  AnimeItem(
    title: 'High School DxD',
    rating: 4.4,
    year: '2024',
    episodes: 48,
    category: 'Эротик',
    description: '18+ контент.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.red,
  ),
  AnimeItem(
    title: 'Prison School',
    rating: 4.5,
    year: '2024',
    episodes: 12,
    category: 'Эротик',
    description: 'Сургуулийн шорон.',
    isLiked: false,
    imagePath: 'assets/attack.jpg',
    color: Colors.orange,
  ),
  AnimeItem(
    title: 'Food Wars',
    rating: 4.6,
    year: '2024',
    episodes: 86,
    category: 'Эротик',
    description: 'Хоолны тэмцээн.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.yellow,
  ),
  AnimeItem(
    title: 'Monster Musume',
    rating: 4.3,
    year: '2024',
    episodes: 12,
    category: 'Эротик',
    description: 'Мангас охид.',
    isLiked: false,
    imagePath: 'assets/dragon.jpg',
    color: Colors.green,
  ),
  AnimeItem(
    title: 'To Love Ru',
    rating: 4.4,
    year: '2024',
    episodes: 64,
    category: 'Эротик',
    description: 'Харем инээдэм.',
    isLiked: false,
    imagePath: 'assets/charlotte.jpg',
    color: Colors.pink,
  ),

  // АНИМЭЙШН - 5 ширхэг
  AnimeItem(
    title: 'Arcane',
    rating: 4.9,
    year: '2024',
    episodes: 9,
    category: 'Анимэйшн',
    description: 'Netflix анимэйшн.',
    isLiked: false,
    imagePath: 'assets/attack.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'Cyberpunk Edgerunners',
    rating: 4.8,
    year: '2024',
    episodes: 10,
    category: 'Анимэйшн',
    description: 'Кибер панк түүх.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.cyan,
  ),
  AnimeItem(
    title: 'Castlevania',
    rating: 4.7,
    year: '2024',
    episodes: 32,
    category: 'Анимэйшн',
    description: 'Дракулагийн түүх.',
    isLiked: false,
    imagePath: 'assets/dragon.jpg',
    color: Colors.red,
  ),
  AnimeItem(
    title: 'Love Death Robots',
    rating: 4.6,
    year: '2024',
    episodes: 35,
    category: 'Анимэйшн',
    description: 'Sci-fi богино түүх.',
    isLiked: false,
    imagePath: 'assets/spy.jpg',
    color: Colors.purple,
  ),
  AnimeItem(
    title: 'Spider-Man Into the Spider-Verse',
    rating: 4.9,
    year: '2024',
    episodes: 1,
    category: 'Анимэйшн',
    description: 'Супер баатрын түүх.',
    isLiked: false,
    imagePath: 'assets/naruto.jpg',
    color: Colors.red,
  ),

  // ИХ ҮЗЭЛТТЭЙ - 5 ширхэг
  AnimeItem(
    title: 'Fullmetal Alchemist',
    rating: 5.0,
    year: '2009',
    episodes: 64,
    category: 'Их үзэлттэй',
    description: 'Хамгийн шилдэг анимэ.',
    isLiked: false,
    imagePath: 'assets/dragon.jpg',
    color: Colors.yellow,
  ),
  AnimeItem(
    title: 'Attack on Titan',
    rating: 4.9,
    year: '2024',
    episodes: 87,
    category: 'Их үзэлттэй',
    description: 'Үлэмж биетний түүх.',
    isLiked: false,
    imagePath: 'assets/attack.jpg',
    color: Colors.brown,
  ),
  AnimeItem(
    title: 'Death Note',
    rating: 5.0,
    year: '2024',
    episodes: 37,
    category: 'Их үзэлттэй',
    description: 'Оюуны тулаан.',
    isLiked: false,
    imagePath: 'assets/silent.jpg',
    color: Colors.black,
  ),
  AnimeItem(
    title: 'One Piece',
    rating: 5.0,
    year: '2024',
    episodes: 1100,
    category: 'Их үзэлттэй',
    description: 'Хамгийн урт анимэ.',
    isLiked: false,
    imagePath: 'assets/one_piece.jpg',
    color: Colors.blue,
  ),
  AnimeItem(
    title: 'Demon Slayer',
    rating: 4.8,
    year: '2024',
    episodes: 55,
    category: 'Их үзэлттэй',
    description: 'Чөтгөр устгагч.',
    isLiked: false,
    imagePath: 'assets/demon.jpg',
    color: Colors.red,
  ),
];