import 'package:flutter/material.dart';
import 'kino_nuur.dart';
class MovieItem {
  String title;
  double rating;
  String year;
  int episodes;
  String category;
  String description;
  bool isLiked;
  String imagePath;
  Color color;

  MovieItem({
    required this.title,
    required this.rating,
    required this.year,
    required this.episodes,
    required this.category,
    required this.description,
    required this.isLiked,
    required this.imagePath,
    required this.color,
  });
}

final List<MovieItem> movieList = [
  MovieItem(
    title: 'Escape',
    rating: 4.5,
    year: '2025',
    episodes: 24,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Escape',
    rating: 4.5,
    year: '2025',
    episodes: 23,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Escape',
    rating: 4.5,
    year: '2025',
    episodes: 22,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Escape',
    rating: 4.5,
    year: '2025',
    episodes: 21,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Escape',
    rating: 4.5,
    year: '2025',
    episodes: 20,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Escape',
    rating: 4.5,
    year: '2025',
    episodes: 19,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Escape',
    rating: 4.5,
    year: '2025',
    episodes: 18,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Escape',
    rating: 4.5,
    year: '2025',
    episodes: 17,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Escape',
    rating: 4.5,
    year: '2025',
    episodes: 16,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Escape',
    rating: 4.5,
    year: '2025',
    episodes: 15,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Escape',
    rating: 4.5,
    year: '2025',
    episodes: 14,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Escape',
    rating: 4.5,
    year: '2025',
    episodes: 13,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Escape',
    rating: 4.5,
    year: '2025',
    episodes: 12,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Escape',
    rating: 4.5,
    year: '2025',
    episodes: 11,
    category: 'Үргэлжлүүлэх',
    description: 'Хүчирхэг баатрын тулааны түүх.',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),

//Шинэ гаралтууд
  MovieItem(
    title: 'Queen For Seven Days',
    rating: 4.8,
    year: '2024',
    episodes: 24,
    category: 'Шинэ гаргалтууд',
    description: 'Queen for seven days',
    isLiked: false,
    imagePath: 'assets/deadly_illusions.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Love',
    rating: 5.0,
    year: '2025',
    episodes: 28,
    category: 'Шинэ гаргалтууд',
    description: 'Love.',
    isLiked: false,
    imagePath: 'assets/love911.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'My unfortunate boyfriend',
    rating: 4.7,
    year: '2025',
    episodes: 25,
    category: 'Шинэ гаргалтууд',
    description: 'My unfortunate boyfriend',
    isLiked: false,
    imagePath: 'assets/my_worst_neighbor.jpg',
    color: Colors.grey,
  ),
  MovieItem(
    title: 'Pale Moon',
    rating: 4.9,
    year: '2025',
    episodes: 26,
    category: 'Шинэ гаргалтууд',
    description: 'Pale Moon',
    isLiked: false,
    imagePath: 'assets/dirty_money.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Justice',
    rating: 4.6,
    year: '2025',
    episodes: 12,
    category: 'Шинэ гаргалтууд',
    description: 'Justice',
    isLiked: false,
    imagePath: 'assets/nezha.jpg',
    color: Colors.amber,
  ),
  MovieItem(
    title: 'Korea-Khitan War',
    rating: 4.9,
    year: '2025',
    episodes: 24,
    category: 'Шинэ гаргалтууд',
    description: 'Korea-Khitan War',
    isLiked: false,
    imagePath: 'assets/front_line.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: 'Andante',
    rating: 4.5,
    year: '2025',
    episodes: 12,
    category: 'Шинэ гаргалтууд',
    description: 'Andante.',
    isLiked: false,
    imagePath: 'assets/mob_psycho.jpg',
    color: Colors.grey,
  ),
  MovieItem(
    title: 'Beyond evil',
    rating: 4.7,
    year: '2025',
    episodes: 12,
    category: 'Шинэ гаргалтууд',
    description: 'Beyond evil.',
    isLiked: false,
    imagePath: 'assets/lady_daddy.jpg',
    color: Colors.pink,
  ),
  MovieItem(
    title: 'Are you human',
    rating: 4.8,
    year: '2025',
    episodes: 24,
    category: 'Шинэ гаргалтууд',
    description: 'Are you human.',
    isLiked: false,
    imagePath: 'assets/following.jpg',
    color: Colors.indigo,
  ),
  MovieItem(
    title: 'Not others',
    rating: 4.6,
    year: '2025',
    episodes: 13,
    category: 'Шинэ гаргалтууд',
    description: 'Not others.',
    isLiked: false,
    imagePath: 'assets/goodrich.jpg',
    color: Colors.cyan,
  ),
  //Адал явдалт
  MovieItem(
    title: 'Escape',
    rating: 4.5,
    year: '2024',
    episodes: 1,
    category: 'Адал явдалт',
    description: 'Escape.',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.grey,
  ),

  MovieItem(
    title: 'Project silence',
    rating: 4.5,
    year: '2023',
    episodes: 1,
    category: 'Адал явдалт',
    description: 'Ёстой мэдэхгүй кино байна.',
    isLiked: false,
    imagePath: 'assets/project_silence.jpg',
    color: Colors.grey,
  ),

  MovieItem(
    title: 'White Bird',
    rating: 4.5,
    year: '2024',
    episodes: 1,
    category: 'Адал явдалт',
    description: 'Ёстой мэдэхгүй кино байна.',
    isLiked: false,
    imagePath: 'assets/white_bird.jpg',
    color: Colors.grey,
  ),

  MovieItem(
    title: 'Inside men',
    rating: 4.7,
    year: '2015',
    episodes: 1,
    category: 'Адал явдалт',
    description: 'Inside man.',
    isLiked: false,
    imagePath: 'assets/inside_men.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Operation UNDEAD',
    rating: 4.8,
    year: '2024',
    episodes: 1,
    category: 'Адал явдалт',
    description: 'Operation undead',
    isLiked: false,
    imagePath: 'assets/operation_undead.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'The silent hour',
    rating: 4.6,
    year: '2024',
    episodes: 1,
    category: 'Адал явдалт',
    description: 'Буутай.',
    isLiked: false,
    imagePath: 'assets/thieves.jpg',
    color: Colors.grey,
  ),
  MovieItem(
    title: 'White Bird',
    rating: 4.6,
    year: '2024',
    episodes: 1,
    category: 'Адал явдалт',
    description: 'Буутай.',
    isLiked: false,
    imagePath: 'assets/white_bird.jpg',
    color: Colors.grey,
  ),
  MovieItem(
    title: 'Escape',
    rating: 4.5,
    year: '2024',
    episodes: 1,
    category: 'Адал явдалт',
    description: 'Escape.',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.grey,
  ),

  MovieItem(
    title: 'Project silence',
    rating: 4.5,
    year: '2023',
    episodes: 1,
    category: 'Адал явдалт',
    description: 'Ёстой мэдэхгүй кино байна.',
    isLiked: false,
    imagePath: 'assets/project_silence.jpg',
    color: Colors.grey,
  ),

  MovieItem(
    title: 'White Bird',
    rating: 4.5,
    year: '2024',
    episodes: 1,
    category: 'Адал явдалт',
    description: 'Ёстой мэдэхгүй кино байна.',
    isLiked: false,
    imagePath: 'assets/white_bird.jpg',
    color: Colors.grey,
  ),

  MovieItem(
    title: 'Inside men',
    rating: 4.7,
    year: '2015',
    episodes: 1,
    category: 'Адал явдалт',
    description: 'Inside man.',
    isLiked: false,
    imagePath: 'assets/inside_men.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Operation UNDEAD',
    rating: 4.8,
    year: '2024',
    episodes: 1,
    category: 'Адал явдалт',
    description: 'Operation undead',
    isLiked: false,
    imagePath: 'assets/operation_undead.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'The silent hour',
    rating: 4.6,
    year: '2024',
    episodes: 1,
    category: 'Адал явдалт',
    description: 'Буутай.',
    isLiked: false,
    imagePath: 'assets/thieves.jpg',
    color: Colors.grey,
  ),
  MovieItem(
    title: 'White Bird',
    rating: 4.6,
    year: '2024',
    episodes: 1,
    category: 'Адал явдалт',
    description: 'Буутай.',
    isLiked: false,
    imagePath: 'assets/white_bird.jpg',
    color: Colors.grey,
  ),


  //Инээдэм 6 кино

  MovieItem(
    title: 'My worst neighbor',
    rating: 4.5,
    year: '2023',
    episodes: 1,
    category: 'Инээдэм',
    description: 'neighbor.',
    isLiked: false,
    imagePath: 'assets/my_worst_neighbor.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Home town',
    rating: 4.6,
    year: '2022',
    episodes: 1,
    category: 'Инээдэм',
    description: 'Инээдэм адал явдал.',
    isLiked: false,
    imagePath: 'assets/home_town.jpg',
    color: Colors.cyan,
  ),

  MovieItem(
    title: 'Panda plan',
    rating: 5.0,
    year: '2024',
    episodes: 1,
    category: 'Инээдэм',
    description: 'Panda.',
    isLiked: false,
    imagePath: 'assets/pandaplan.jpg',
    color: Colors.black,
  ),
  MovieItem(
    title: 'ээ дээ... энэ эрчүүд үү?',
    rating: 4.9,
    year: '2024',
    episodes: 1,
    category: 'Инээдэм',
    description: 'Эрчүүдээ гэж...',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Amazon bullseye',
    rating: 4.8,
    year: '2024',
    episodes: 1,
    category: 'Инээдэм',
    description: 'Ширэнгэн ой.',
    isLiked: false,
    imagePath: 'assets/amazon.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Love 911',
    rating: 5.0,
    year: '2012',
    episodes: 1,
    category: 'Инээдэм',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/love911.jpg',
    color: Colors.yellow,
  ),
  MovieItem(
    title: 'My worst neighbor',
    rating: 4.5,
    year: '2023',
    episodes: 1,
    category: 'Инээдэм',
    description: 'neighbor.',
    isLiked: false,
    imagePath: 'assets/my_worst_neighbor.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Home town',
    rating: 4.6,
    year: '2022',
    episodes: 1,
    category: 'Инээдэм',
    description: 'Инээдэм адал явдал.',
    isLiked: false,
    imagePath: 'assets/home_town.jpg',
    color: Colors.cyan,
  ),

  MovieItem(
    title: 'Panda plan',
    rating: 5.0,
    year: '2024',
    episodes: 1,
    category: 'Инээдэм',
    description: 'Panda.',
    isLiked: false,
    imagePath: 'assets/pandaplan.jpg',
    color: Colors.black,
  ),
  MovieItem(
    title: 'ээ дээ... энэ эрчүүд үү?',
    rating: 4.9,
    year: '2024',
    episodes: 1,
    category: 'Инээдэм',
    description: 'Эрчүүдээ гэж...',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Amazon bullseye',
    rating: 4.8,
    year: '2024',
    episodes: 1,
    category: 'Инээдэм',
    description: 'Ширэнгэн ой.',
    isLiked: false,
    imagePath: 'assets/amazon.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Love 911',
    rating: 5.0,
    year: '2012',
    episodes: 1,
    category: 'Инээдэм',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/love911.jpg',
    color: Colors.yellow,
  ),
  MovieItem(
    title: 'My worst neighbor',
    rating: 4.5,
    year: '2023',
    episodes: 1,
    category: 'Инээдэм',
    description: 'neighbor.',
    isLiked: false,
    imagePath: 'assets/my_worst_neighbor.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Home town',
    rating: 4.6,
    year: '2022',
    episodes: 1,
    category: 'Инээдэм',
    description: 'Инээдэм адал явдал.',
    isLiked: false,
    imagePath: 'assets/home_town.jpg',
    color: Colors.cyan,
  ),

  MovieItem(
    title: 'Panda plan',
    rating: 5.0,
    year: '2024',
    episodes: 1,
    category: 'Инээдэм',
    description: 'Panda.',
    isLiked: false,
    imagePath: 'assets/pandaplan.jpg',
    color: Colors.black,
  ),
  MovieItem(
    title: 'ээ дээ... энэ эрчүүд үү?',
    rating: 4.9,
    year: '2024',
    episodes: 1,
    category: 'Инээдэм',
    description: 'Эрчүүдээ гэж...',
    isLiked: false,
    imagePath: 'assets/escape.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Amazon bullseye',
    rating: 4.8,
    year: '2024',
    episodes: 1,
    category: 'Инээдэм',
    description: 'Ширэнгэн ой.',
    isLiked: false,
    imagePath: 'assets/amazon.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Love 911',
    rating: 5.0,
    year: '2012',
    episodes: 1,
    category: 'Инээдэм',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/love911.jpg',
    color: Colors.yellow,
  ),
  //Энтертайнмент & тоглолт
  MovieItem(
    title: 'Davaidasha: Шоколад Live concert',
    rating: 4.9,
    year: '2011',
    episodes: 148,
    category: 'Энтертайнмент & тоглолт',
    description: 'Тоглолт.',
    isLiked: false,
    imagePath: 'assets/davaidasha.jpg',
    color: Colors.green,
  ),

  MovieItem(
    title: 'XIA Concert Movie Chapter 1 Recration',
    rating: 4.7,
    year: '2024',
    episodes: 24,
    category: 'Энтертайнмент & тоглолт',
    description: 'IDOL.',
    isLiked: false,
    imagePath: 'assets/xia_concert.jpg',
    color: Colors.green,
  ),
  MovieItem(
    title: 'Aespa: My first page',
    rating: 4.6,
    year: '2024',
    episodes: 1,
    category: 'Энтертайнмент & тоглолт',
    description: 'Мюзикл.',
    isLiked: false,
    imagePath: 'assets/aespa.png',
    color: Colors.red,
  ),
  MovieItem(
    title: 'Rokit bay',
    rating: 4.7,
    year: '2022',
    episodes: 1,
    category: 'Энтертайнмент & тоглолт',
    description: 'Монгол.',
    isLiked: false,
    imagePath: 'assets/rokitbay.jpg',
    color: Colors.blue,
  ),
  //Дурсамж сэргэм
  MovieItem(
    title: 'Цусаа худалдагчийн түүх',
    rating: 4.5,
    year: '2015',
    episodes: 1,
    category: 'Дурсамж сэргэм',
    description: 'Цус.',
    isLiked: false,
    imagePath: 'assets/tsus_hudaldagch.jpg',
    color: Colors.brown,
  ),
  MovieItem(
    title: 'Миний бодлын баллуур',
    rating: 4.6,
    year: '2004',
    episodes: 36,
    category: 'Дурсамж сэргэм',
    description: 'Хайрлана гэдэг сайхан.',
    isLiked: false,
    imagePath: 'assets/minii_bodliin_balluur.jpg',
    color: Colors.purple,
  ),

  MovieItem(
    title: 'The front line, last battle of the korean war',
    rating: 4.8,
    year: '2011',
    episodes: 1,
    category: 'Дурсамж сэргэм',
    description: 'Солонгосын дайн.',
    isLiked: false,
    imagePath: 'assets/front_line.jpg',
    color: Colors.pink,
  ),
  MovieItem(
    title: 'The thieves',
    rating: 4.7,
    year: '2012',
    episodes: 1,
    category: 'Дурсамж сэргэм',
    description: 'Алмазын хулгай.',
    isLiked: false,
    imagePath: 'assets/thieves.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Найз 2 өв залгамжлал',
    rating: 4.9,
    year: '2013',
    episodes: 1,
    category: 'Дурсамж сэргэм',
    description: 'Мэдэхгүй.',
    isLiked: false,
    imagePath: 'assets/friend2.jpeg',
    color: Colors.pink,
  ),
  MovieItem(
    title: 'Бохир гудамж',
    rating: 4.7,
    year: '2025',
    episodes: 1,
    category: 'Дурсамж сэргэм',
    description: 'Зодоон.',
    isLiked: false,
    imagePath: 'assets/dirty_street.jpg',
    color: Colors.lightBlue,
  ),
  MovieItem(
    title: 'Цусаа худалдагчийн түүх',
    rating: 4.5,
    year: '2015',
    episodes: 1,
    category: 'Дурсамж сэргэм',
    description: 'Цус.',
    isLiked: false,
    imagePath: 'assets/tsus_hudaldagch.jpg',
    color: Colors.brown,
  ),
  MovieItem(
    title: 'Миний бодлын баллуур',
    rating: 4.6,
    year: '2004',
    episodes: 36,
    category: 'Дурсамж сэргэм',
    description: 'Хайрлана гэдэг сайхан.',
    isLiked: false,
    imagePath: 'assets/minii_bodliin_balluur.jpg',
    color: Colors.purple,
  ),

  MovieItem(
    title: 'The front line, last battle of the korean war',
    rating: 4.8,
    year: '2011',
    episodes: 1,
    category: 'Дурсамж сэргэм',
    description: 'Солонгосын дайн.',
    isLiked: false,
    imagePath: 'assets/front_line.jpg',
    color: Colors.pink,
  ),
  MovieItem(
    title: 'The thieves',
    rating: 4.7,
    year: '2012',
    episodes: 1,
    category: 'Дурсамж сэргэм',
    description: 'Алмазын хулгай.',
    isLiked: false,
    imagePath: 'assets/thieves.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Найз 2 өв залгамжлал',
    rating: 4.9,
    year: '2013',
    episodes: 1,
    category: 'Дурсамж сэргэм',
    description: 'Мэдэхгүй.',
    isLiked: false,
    imagePath: 'assets/friend2.jpeg',
    color: Colors.pink,
  ),
  MovieItem(
    title: 'Бохир гудамж',
    rating: 4.7,
    year: '2025',
    episodes: 1,
    category: 'Дурсамж сэргэм',
    description: 'Зодоон.',
    isLiked: false,
    imagePath: 'assets/dirty_street.jpg',
    color: Colors.lightBlue,
  ),
  //Хайр дурлал
  MovieItem(
    title: 'Love in the big city',
    rating: 4.8,
    year: '2024',
    episodes: 1,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/veteran2.jpg',
    color: Colors.purple,
  ),

  MovieItem(
    title: 'Love my scent',
    rating: 4.5,
    year: '2024',
    episodes: 12,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/love_in_the_big_city.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Love 911',
    rating: 4.3,
    year: '2024',
    episodes: 10,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/love911.jpg',
    color: Colors.green,
  ),
  MovieItem(
    title: 'Lady daddy',
    rating: 4.4,
    year: '2024',
    episodes: 8,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/lady_daddy.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: 'Миний найз охин 2 нүүртэн',
    rating: 4.2,
    year: '2024',
    episodes: 15,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/hoer_nuurten.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Адамас',
    rating: 4.6,
    year: '2024',
    episodes: 20,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/adamas.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Love in the big city',
    rating: 4.8,
    year: '2024',
    episodes: 1,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/veteran2.jpg',
    color: Colors.purple,
  ),

  MovieItem(
    title: 'Love my scent',
    rating: 4.5,
    year: '2024',
    episodes: 12,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/love_in_the_big_city.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Love 911',
    rating: 4.3,
    year: '2024',
    episodes: 10,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/love911.jpg',
    color: Colors.green,
  ),
  MovieItem(
    title: 'Lady daddy',
    rating: 4.4,
    year: '2024',
    episodes: 8,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/lady_daddy.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: 'Миний найз охин 2 нүүртэн',
    rating: 4.2,
    year: '2024',
    episodes: 15,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/hoer_nuurten.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Адамас',
    rating: 4.6,
    year: '2024',
    episodes: 20,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/adamas.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Love in the big city',
    rating: 4.8,
    year: '2024',
    episodes: 1,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/veteran2.jpg',
    color: Colors.purple,
  ),

  MovieItem(
    title: 'Love my scent',
    rating: 4.5,
    year: '2024',
    episodes: 12,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/love_in_the_big_city.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Love 911',
    rating: 4.3,
    year: '2024',
    episodes: 10,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/love911.jpg',
    color: Colors.green,
  ),
  MovieItem(
    title: 'Lady daddy',
    rating: 4.4,
    year: '2024',
    episodes: 8,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/lady_daddy.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: 'Миний найз охин 2 нүүртэн',
    rating: 4.2,
    year: '2024',
    episodes: 15,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/hoer_nuurten.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Адамас',
    rating: 4.6,
    year: '2024',
    episodes: 20,
    category: 'Хайр дурлал',
    description: 'Хайр.',
    isLiked: false,
    imagePath: 'assets/adamas.jpg',
    color: Colors.purple,
  ),
  // Багачуудад
  MovieItem(
    title: 'Runt',
    rating: 4.8,
    year: '2024',
    episodes: 23,
    category: 'Багачуудад',
    description: 'Дайны хүнд түүх.',
    isLiked: false,
    imagePath: 'assets/runt.jpg',
    color: Colors.grey,
  ),
  MovieItem(
    title: '100% wolf',
    rating: 4.6,
    year: '2024',
    episodes: 24,
    category: 'Багачуудад',
    description: 'Цэргийн адал явдал.',
    isLiked: false,
    imagePath: 'assets/100wolf.jpg',
    color: Colors.green,
  ),
  MovieItem(
    title: 'Dogs opera',
    rating: 4.5,
    year: '2024',
    episodes: 24,
    category: 'Багачуудад',
    description: 'Робот цэргийн түүх.',
    isLiked: false,
    imagePath: 'assets/dogs_opera.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Here comes the Grump',
    rating: 4.7,
    year: '2024',
    episodes: 12,
    category: 'Багачуудад',
    description: 'Дайны охины түүх.',
    isLiked: false,
    imagePath: 'assets/here_comes_the_grump.jpg',
    color: Colors.brown,
  ),
  MovieItem(
    title: 'Nezha',
    rating: 4.4,
    year: '2024',
    episodes: 13,
    category: 'Багачуудад',
    description: 'Тактикийн ухааны түүх.',
    isLiked: false,
    imagePath: 'assets/nezha.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: 'Runt',
    rating: 4.8,
    year: '2024',
    episodes: 23,
    category: 'Багачуудад',
    description: 'Дайны хүнд түүх.',
    isLiked: false,
    imagePath: 'assets/runt.jpg',
    color: Colors.grey,
  ),
  MovieItem(
    title: '100% wolf',
    rating: 4.6,
    year: '2024',
    episodes: 24,
    category: 'Багачуудад',
    description: 'Цэргийн адал явдал.',
    isLiked: false,
    imagePath: 'assets/100wolf.jpg',
    color: Colors.green,
  ),
  MovieItem(
    title: 'Dogs opera',
    rating: 4.5,
    year: '2024',
    episodes: 24,
    category: 'Багачуудад',
    description: 'Робот цэргийн түүх.',
    isLiked: false,
    imagePath: 'assets/dogs_opera.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Here comes the Grump',
    rating: 4.7,
    year: '2024',
    episodes: 12,
    category: 'Багачуудад',
    description: 'Дайны охины түүх.',
    isLiked: false,
    imagePath: 'assets/here_comes_the_grump.jpg',
    color: Colors.brown,
  ),
  MovieItem(
    title: 'Nezha',
    rating: 4.4,
    year: '2024',
    episodes: 13,
    category: 'Багачуудад',
    description: 'Тактикийн ухааны түүх.',
    isLiked: false,
    imagePath: 'assets/nezha.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: 'Runt',
    rating: 4.8,
    year: '2024',
    episodes: 23,
    category: 'Багачуудад',
    description: 'Дайны хүнд түүх.',
    isLiked: false,
    imagePath: 'assets/runt.jpg',
    color: Colors.grey,
  ),
  MovieItem(
    title: '100% wolf',
    rating: 4.6,
    year: '2024',
    episodes: 24,
    category: 'Багачуудад',
    description: 'Цэргийн адал явдал.',
    isLiked: false,
    imagePath: 'assets/100wolf.jpg',
    color: Colors.green,
  ),
  MovieItem(
    title: 'Dogs opera',
    rating: 4.5,
    year: '2024',
    episodes: 24,
    category: 'Багачуудад',
    description: 'Робот цэргийн түүх.',
    isLiked: false,
    imagePath: 'assets/dogs_opera.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Here comes the Grump',
    rating: 4.7,
    year: '2024',
    episodes: 12,
    category: 'Багачуудад',
    description: 'Дайны охины түүх.',
    isLiked: false,
    imagePath: 'assets/here_comes_the_grump.jpg',
    color: Colors.brown,
  ),
  MovieItem(
    title: 'Nezha',
    rating: 4.4,
    year: '2024',
    episodes: 13,
    category: 'Багачуудад',
    description: 'Тактикийн ухааны түүх.',
    isLiked: false,
    imagePath: 'assets/nezha.jpg',
    color: Colors.red,
  ),
  //Гэр бүл
  MovieItem(
    title: 'The flying ship',
    rating: 4.9,
    year: '2024',
    episodes: 24,
    category: 'Гэр бүл',
    description: 'Нисдэг хөлөг онгоц.',
    isLiked: false,
    imagePath: 'assets/flying_ship.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'The inseparables',
    rating: 4.5,
    year: '2024',
    episodes: 13,
    category: 'Гэр бүл',
    description: 'Биологийн дэлхий.',
    isLiked: false,
    imagePath: 'assets/inseparable.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: 'Amazing Maurice',
    rating: 4.6,
    year: '2024',
    episodes: 26,
    category: 'Гэр бүл',
    description: 'Сансрын түүх.',
    isLiked: false,
    imagePath: 'assets/amazing_maurice.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'My fairy troublemaker',
    rating: 4.8,
    year: '2024',
    episodes: 26,
    category: 'Гэр бүл',
    description: 'Кибер панк ертөнц.',
    isLiked: false,
    imagePath: 'assets/my_fairy_troublemaker.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'The flying ship',
    rating: 4.9,
    year: '2024',
    episodes: 24,
    category: 'Гэр бүл',
    description: 'Нисдэг хөлөг онгоц.',
    isLiked: false,
    imagePath: 'assets/flying_ship.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'The inseparables',
    rating: 4.5,
    year: '2024',
    episodes: 13,
    category: 'Гэр бүл',
    description: 'Биологийн дэлхий.',
    isLiked: false,
    imagePath: 'assets/inseparable.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: 'Amazing Maurice',
    rating: 4.6,
    year: '2024',
    episodes: 26,
    category: 'Гэр бүл',
    description: 'Сансрын түүх.',
    isLiked: false,
    imagePath: 'assets/amazing_maurice.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'My fairy troublemaker',
    rating: 4.8,
    year: '2024',
    episodes: 26,
    category: 'Гэр бүл',
    description: 'Кибер панк ертөнц.',
    isLiked: false,
    imagePath: 'assets/my_fairy_troublemaker.jpg',
    color: Colors.purple,
  ),

  //Драма
  MovieItem(
    title: 'The man standing next',
    rating: 4.7,
    year: '1998',
    episodes: 26,
    category: 'Драма',
    description: 'Баруун өмнөдийн sci-fi.',
    isLiked: false,
    imagePath: 'assets/the_man_standing_next.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Where would you like to go?',
    rating: 4.8,
    year: '1992',
    episodes: 112,
    category: 'Драма',
    description: 'Шоунэн классик.',
    isLiked: false,
    imagePath: 'assets/where_would_u_like_to_go.jpg',
    color: Colors.green,
  ),
  MovieItem(
    title: 'inside men',
    rating: 4.7,
    year: '1996',
    episodes: 94,
    category: 'Драма',
    description: 'Самурайн түүх.',
    isLiked: false,
    imagePath: 'assets/inside_men.jpg',
    color: Colors.red,
  ),

  MovieItem(
    title: 'Land of happiness',
    rating: 4.7,
    year: '2024',
    episodes: 75,
    category: 'Драма',
    description: 'Сагсан бөмбөгийн түүх.',
    isLiked: false,
    imagePath: 'assets/land_of_happiness.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Goodrich',
    rating: 4.8,
    year: '2024',
    episodes: 101,
    category: 'Драма',
    description: 'Сагсны классик.',
    isLiked: false,
    imagePath: 'assets/goodrich.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: 'The man standing next',
    rating: 4.7,
    year: '1998',
    episodes: 26,
    category: 'Драма',
    description: 'Баруун өмнөдийн sci-fi.',
    isLiked: false,
    imagePath: 'assets/the_man_standing_next.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Where would you like to go?',
    rating: 4.8,
    year: '1992',
    episodes: 112,
    category: 'Драма',
    description: 'Шоунэн классик.',
    isLiked: false,
    imagePath: 'assets/where_would_u_like_to_go.jpg',
    color: Colors.green,
  ),
  MovieItem(
    title: 'inside men',
    rating: 4.7,
    year: '1996',
    episodes: 94,
    category: 'Драма',
    description: 'Самурайн түүх.',
    isLiked: false,
    imagePath: 'assets/inside_men.jpg',
    color: Colors.red,
  ),

  MovieItem(
    title: 'Land of happiness',
    rating: 4.7,
    year: '2024',
    episodes: 75,
    category: 'Драма',
    description: 'Сагсан бөмбөгийн түүх.',
    isLiked: false,
    imagePath: 'assets/land_of_happiness.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Goodrich',
    rating: 4.8,
    year: '2024',
    episodes: 101,
    category: 'Драма',
    description: 'Сагсны классик.',
    isLiked: false,
    imagePath: 'assets/goodrich.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: 'The man standing next',
    rating: 4.7,
    year: '1998',
    episodes: 26,
    category: 'Драма',
    description: 'Баруун өмнөдийн sci-fi.',
    isLiked: false,
    imagePath: 'assets/the_man_standing_next.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Where would you like to go?',
    rating: 4.8,
    year: '1992',
    episodes: 112,
    category: 'Драма',
    description: 'Шоунэн классик.',
    isLiked: false,
    imagePath: 'assets/where_would_u_like_to_go.jpg',
    color: Colors.green,
  ),
  MovieItem(
    title: 'inside men',
    rating: 4.7,
    year: '1996',
    episodes: 94,
    category: 'Драма',
    description: 'Самурайн түүх.',
    isLiked: false,
    imagePath: 'assets/inside_men.jpg',
    color: Colors.red,
  ),

  MovieItem(
    title: 'Land of happiness',
    rating: 4.7,
    year: '2024',
    episodes: 75,
    category: 'Драма',
    description: 'Сагсан бөмбөгийн түүх.',
    isLiked: false,
    imagePath: 'assets/land_of_happiness.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Goodrich',
    rating: 4.8,
    year: '2024',
    episodes: 101,
    category: 'Драма',
    description: 'Сагсны классик.',
    isLiked: false,
    imagePath: 'assets/goodrich.jpg',
    color: Colors.red,
  ),
  //Би айжийна
  MovieItem(
    title: 'Helpless',
    rating: 4.6,
    year: '2024',
    episodes: 24,
    category: 'Би айжийна',
    description: 'Хөлбөмбөгийн тэргүүн.',
    isLiked: false,
    imagePath: 'assets/helpless.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Strange darling',
    rating: 4.8,
    year: '2024',
    episodes: 75,
    category: 'Би айжийна',
    description: 'Боксчны замнал.',
    isLiked: false,
    imagePath: 'assets/strange_darling.jpg',
    color: Colors.brown,
  ),

  MovieItem(
    title: 'The man standing next',
    rating: 4.8,
    year: '2004',
    episodes: 74,
    category: 'Би айжийна',
    description: 'Гэмт хэргийн түүх.',
    isLiked: false,
    imagePath: 'assets/the_man_standing_next.jpg',
    color: Colors.grey,
  ),
  MovieItem(
    title: 'Fliht risk',
    rating: 4.7,
    year: '2024',
    episodes: 1000,
    category: 'Би айжийна',
    description: 'Мөрдөгчийн түүх.',
    isLiked: false,
    imagePath: 'assets/flight_risk.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Wannabe',
    rating: 5.0,
    year: '2024',
    episodes: 37,
    category: 'Би айжийна',
    description: 'Оюуны тулаан.',
    isLiked: false,
    imagePath: 'assets/wannabe.jpg',
    color: Colors.black,
  ),
  //Уран зөгнөлт
  MovieItem(
    title: 'The stronghold',
    rating: 4.7,
    year: '2024',
    episodes: 12,
    category: 'Уран зөгнөлт',
    description: 'Цаг хугацааны мөрдөн байцаалт.',
    isLiked: false,
    imagePath: 'assets/stronghold.jpg',
    color: Colors.blue,
  ),

  MovieItem(
    title: 'Alienoid',
    rating: 4.7,
    year: '2024',
    episodes: 25,
    category: 'Уран зөгнөлт',
    description: 'Супер баатрууд.',
    isLiked: false,
    imagePath: 'assets/aleinoid.jpg',
    color: Colors.green,
  ),
  MovieItem(
    title: 'Dr. Cheon',
    rating: 4.9,
    year: '2024',
    episodes: 24,
    category: 'Уран зөгнөлт',
    description: 'Нэг цохилтын баатар.',
    isLiked: false,
    imagePath: 'assets/dr_cheon.jpg',
    color: Colors.yellow,
  ),
  MovieItem(
    title: 'Mob Psycho 100',
    rating: 4.8,
    year: '2024',
    episodes: 25,
    category: 'Уран зөгнөлт',
    description: 'Сэтгэцийн хүч.',
    isLiked: false,
    imagePath: 'assets/mob_psycho.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Robortbror',
    rating: 4.6,
    year: '2024',
    episodes: 13,
    category: 'Уран зөгнөлт',
    description: 'Онцгой чадвартай залуучууд.',
    isLiked: false,
    imagePath: 'assets/robortbror.jpg',
    color: Colors.blue,
  ),

  // Аймшгийн
  MovieItem(
    title: 'Never let go',
    rating: 4.8,
    year: '2024',
    episodes: 12,
    category: 'Аймшгийн',
    description: 'Хятадын анимэ.',
    isLiked: false,
    imagePath: 'assets/never_let_go.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Bagman',
    rating: 4.7,
    year: '2024',
    episodes: 23,
    category: 'Аймшгийн',
    description: 'Хятад фэнтэзи.',
    isLiked: false,
    imagePath: 'assets/bagman.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Spring Garden',
    rating: 4.6,
    year: '2024',
    episodes: 12,
    category: 'Аймшгийн',
    description: 'Е-спортын түүх.',
    isLiked: false,
    imagePath: 'assets/spring_garden.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Long legs',
    rating: 4.5,
    year: '2024',
    episodes: 30,
    category: 'Аймшгийн',
    description: 'Инээдтэй үйлдэл.',
    isLiked: false,
    imagePath: 'assets/longlegs.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: '4:44',
    rating: 4.7,
    year: '2024',
    episodes: 12,
    category: 'Аймшгийн',
    description: 'Тэнгэрийн үүлэнд.',
    isLiked: false,
    imagePath: 'assets/444.jpg',
    color: Colors.cyan,
  ),
  MovieItem(
    title: 'Never let go',
    rating: 4.8,
    year: '2024',
    episodes: 12,
    category: 'Аймшгийн',
    description: 'Хятадын анимэ.',
    isLiked: false,
    imagePath: 'assets/never_let_go.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Bagman',
    rating: 4.7,
    year: '2024',
    episodes: 23,
    category: 'Аймшгийн',
    description: 'Хятад фэнтэзи.',
    isLiked: false,
    imagePath: 'assets/bagman.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Spring Garden',
    rating: 4.6,
    year: '2024',
    episodes: 12,
    category: 'Аймшгийн',
    description: 'Е-спортын түүх.',
    isLiked: false,
    imagePath: 'assets/spring_garden.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Long legs',
    rating: 4.5,
    year: '2024',
    episodes: 30,
    category: 'Аймшгийн',
    description: 'Инээдтэй үйлдэл.',
    isLiked: false,
    imagePath: 'assets/longlegs.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: '4:44',
    rating: 4.7,
    year: '2024',
    episodes: 12,
    category: 'Аймшгийн',
    description: 'Тэнгэрийн үүлэнд.',
    isLiked: false,
    imagePath: 'assets/444.jpg',
    color: Colors.cyan,
  ),
  MovieItem(
    title: 'Never let go',
    rating: 4.8,
    year: '2024',
    episodes: 12,
    category: 'Аймшгийн',
    description: 'Хятадын анимэ.',
    isLiked: false,
    imagePath: 'assets/never_let_go.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Bagman',
    rating: 4.7,
    year: '2024',
    episodes: 23,
    category: 'Аймшгийн',
    description: 'Хятад фэнтэзи.',
    isLiked: false,
    imagePath: 'assets/bagman.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Spring Garden',
    rating: 4.6,
    year: '2024',
    episodes: 12,
    category: 'Аймшгийн',
    description: 'Е-спортын түүх.',
    isLiked: false,
    imagePath: 'assets/spring_garden.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Long legs',
    rating: 4.5,
    year: '2024',
    episodes: 30,
    category: 'Аймшгийн',
    description: 'Инээдтэй үйлдэл.',
    isLiked: false,
    imagePath: 'assets/longlegs.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: '4:44',
    rating: 4.7,
    year: '2024',
    episodes: 12,
    category: 'Аймшгийн',
    description: 'Тэнгэрийн үүлэнд.',
    isLiked: false,
    imagePath: 'assets/444.jpg',
    color: Colors.cyan,
  ),
  MovieItem(
    title: 'Never let go',
    rating: 4.8,
    year: '2024',
    episodes: 12,
    category: 'Аймшгийн',
    description: 'Хятадын анимэ.',
    isLiked: false,
    imagePath: 'assets/never_let_go.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Bagman',
    rating: 4.7,
    year: '2024',
    episodes: 23,
    category: 'Аймшгийн',
    description: 'Хятад фэнтэзи.',
    isLiked: false,
    imagePath: 'assets/bagman.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Spring Garden',
    rating: 4.6,
    year: '2024',
    episodes: 12,
    category: 'Аймшгийн',
    description: 'Е-спортын түүх.',
    isLiked: false,
    imagePath: 'assets/spring_garden.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Long legs',
    rating: 4.5,
    year: '2024',
    episodes: 30,
    category: 'Аймшгийн',
    description: 'Инээдтэй үйлдэл.',
    isLiked: false,
    imagePath: 'assets/longlegs.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: '4:44',
    rating: 4.7,
    year: '2024',
    episodes: 12,
    category: 'Аймшгийн',
    description: 'Тэнгэрийн үүлэнд.',
    isLiked: false,
    imagePath: 'assets/444.jpg',
    color: Colors.cyan,
  ),
  //Гэмт хэрэг
  MovieItem(
    title: 'Veteran 2',
    rating: 4.7,
    year: '2024',
    episodes: 32,
    category: 'Гэмт хэрэг',
    description: 'Дракулагийн түүх.',
    isLiked: false,
    imagePath: 'assets/veteran2.jpg',
    color: Colors.grey,
  ),
  MovieItem(
    title: 'Dirty Money',
    rating: 4.8,
    year: '2024',
    episodes: 10,
    category: 'Гэмт хэрэг',
    description: 'Цус сорогчийн анчин.',
    isLiked: false,
    imagePath: 'assets/dirty_money.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: 'The order',
    rating: 4.6,
    year: '2024',
    episodes: 24,
    category: 'Гэмт хэрэг',
    description: 'Хүмүүс эсрэг цус сорогч.',
    isLiked: false,
    imagePath: 'assets/order.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Inside men',
    rating: 4.5,
    year: '2024',
    episodes: 25,
    category: 'Гэмт хэрэг',
    description: 'Чөтгөр усгацгагч.',
    isLiked: false,
    imagePath: 'assets/inside_men.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Revolver',
    rating: 4.5,
    year: '2024',
    episodes: 25,
    category: 'Гэмт хэрэг',
    description: 'Чөтгөр усгацгагч.',
    isLiked: false,
    imagePath: 'assets/revolver.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Veteran 2',
    rating: 4.7,
    year: '2024',
    episodes: 32,
    category: 'Гэмт хэрэг',
    description: 'Дракулагийн түүх.',
    isLiked: false,
    imagePath: 'assets/veteran2.jpg',
    color: Colors.grey,
  ),
  MovieItem(
    title: 'Dirty Money',
    rating: 4.8,
    year: '2024',
    episodes: 10,
    category: 'Гэмт хэрэг',
    description: 'Цус сорогчийн анчин.',
    isLiked: false,
    imagePath: 'assets/dirty_money.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: 'The order',
    rating: 4.6,
    year: '2024',
    episodes: 24,
    category: 'Гэмт хэрэг',
    description: 'Хүмүүс эсрэг цус сорогч.',
    isLiked: false,
    imagePath: 'assets/order.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Inside men',
    rating: 4.5,
    year: '2024',
    episodes: 25,
    category: 'Гэмт хэрэг',
    description: 'Чөтгөр усгацгагч.',
    isLiked: false,
    imagePath: 'assets/inside_men.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Revolver',
    rating: 4.5,
    year: '2024',
    episodes: 25,
    category: 'Гэмт хэрэг',
    description: 'Чөтгөр усгацгагч.',
    isLiked: false,
    imagePath: 'assets/revolver.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Veteran 2',
    rating: 4.7,
    year: '2024',
    episodes: 32,
    category: 'Гэмт хэрэг',
    description: 'Дракулагийн түүх.',
    isLiked: false,
    imagePath: 'assets/veteran2.jpg',
    color: Colors.grey,
  ),
  MovieItem(
    title: 'Dirty Money',
    rating: 4.8,
    year: '2024',
    episodes: 10,
    category: 'Гэмт хэрэг',
    description: 'Цус сорогчийн анчин.',
    isLiked: false,
    imagePath: 'assets/dirty_money.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: 'The order',
    rating: 4.6,
    year: '2024',
    episodes: 24,
    category: 'Гэмт хэрэг',
    description: 'Хүмүүс эсрэг цус сорогч.',
    isLiked: false,
    imagePath: 'assets/order.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Inside men',
    rating: 4.5,
    year: '2024',
    episodes: 25,
    category: 'Гэмт хэрэг',
    description: 'Чөтгөр усгацгагч.',
    isLiked: false,
    imagePath: 'assets/inside_men.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Revolver',
    rating: 4.5,
    year: '2024',
    episodes: 25,
    category: 'Гэмт хэрэг',
    description: 'Чөтгөр усгацгагч.',
    isLiked: false,
    imagePath: 'assets/revolver.jpg',
    color: Colors.blue,
  ),MovieItem(
    title: 'Veteran 2',
    rating: 4.7,
    year: '2024',
    episodes: 32,
    category: 'Гэмт хэрэг',
    description: 'Дракулагийн түүх.',
    isLiked: false,
    imagePath: 'assets/veteran2.jpg',
    color: Colors.grey,
  ),
  MovieItem(
    title: 'Dirty Money',
    rating: 4.8,
    year: '2024',
    episodes: 10,
    category: 'Гэмт хэрэг',
    description: 'Цус сорогчийн анчин.',
    isLiked: false,
    imagePath: 'assets/dirty_money.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: 'The order',
    rating: 4.6,
    year: '2024',
    episodes: 24,
    category: 'Гэмт хэрэг',
    description: 'Хүмүүс эсрэг цус сорогч.',
    isLiked: false,
    imagePath: 'assets/order.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Inside men',
    rating: 4.5,
    year: '2024',
    episodes: 25,
    category: 'Гэмт хэрэг',
    description: 'Чөтгөр усгацгагч.',
    isLiked: false,
    imagePath: 'assets/inside_men.jpg',
    color: Colors.blue,
  ),
  MovieItem(
    title: 'Revolver',
    rating: 4.5,
    year: '2024',
    episodes: 25,
    category: 'Гэмт хэрэг',
    description: 'Чөтгөр усгацгагч.',
    isLiked: false,
    imagePath: 'assets/revolver.jpg',
    color: Colors.blue,
  ),

  // Нууцлаг
  MovieItem(
    title: 'Exhuma',
    rating: 4.6,
    year: '2024',
    episodes: 12,
    category: 'Нууцлаг',
    description: 'Тоглоомоор ертөнцийг авах.',
    isLiked: false,
    imagePath: 'assets/exhuma.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Following',
    rating: 4.5,
    year: '2024',
    episodes: 24,
    category: 'Нууцлаг',
    description: 'Мөрийтэй тоглоом.',
    isLiked: false,
    imagePath: 'assets/following.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: 'Deadly illusions',
    rating: 4.7,
    year: '2024',
    episodes: 12,
    category: 'Нууцлаг',
    description: 'Үхлийн тоглоом.',
    isLiked: false,
    imagePath: 'assets/deadly_illusions.jpg',
    color: Colors.grey,
  ),
  MovieItem(
    title: 'Hidden face',
    rating: 4.6,
    year: '2024',
    episodes: 26,
    category: 'Нууцлаг',
    description: 'Азартын тоглоом.',
    isLiked: false,
    imagePath: 'assets/hidden_face.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Exhuma',
    rating: 4.6,
    year: '2024',
    episodes: 12,
    category: 'Нууцлаг',
    description: 'Тоглоомоор ертөнцийг авах.',
    isLiked: false,
    imagePath: 'assets/exhuma.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Following',
    rating: 4.5,
    year: '2024',
    episodes: 24,
    category: 'Нууцлаг',
    description: 'Мөрийтэй тоглоом.',
    isLiked: false,
    imagePath: 'assets/following.jpg',
    color: Colors.red,
  ),
  MovieItem(
    title: 'Deadly illusions',
    rating: 4.7,
    year: '2024',
    episodes: 12,
    category: 'Нууцлаг',
    description: 'Үхлийн тоглоом.',
    isLiked: false,
    imagePath: 'assets/deadly_illusions.jpg',
    color: Colors.grey,
  ),
  MovieItem(
    title: 'Hidden face',
    rating: 4.6,
    year: '2024',
    episodes: 26,
    category: 'Нууцлаг',
    description: 'Азартын тоглоом.',
    isLiked: false,
    imagePath: 'assets/hidden_face.jpg',
    color: Colors.orange,
  ),
  MovieItem(
    title: 'Exhuma',
    rating: 4.6,
    year: '2024',
    episodes: 12,
    category: 'Нууцлаг',
    description: 'Тоглоомоор ертөнцийг авах.',
    isLiked: false,
    imagePath: 'assets/exhuma.jpg',
    color: Colors.purple,
  ),
  MovieItem(
    title: 'Following',
    rating: 4.5,
    year: '2024',
    episodes: 24,
    category: 'Нууцлаг',
    description: 'Мөрийтэй тоглоом.',
    isLiked: false,
    imagePath: 'assets/following.jpg',
    color: Colors.red,
  ),

];